image: node:5.11.0-wheezy

stages:
  - test
  - build-and-push

test-job:
  stage: test
  tags:
    - build-in-docker
  script:
    - cd application && npm set progress=false && npm install --silent
    - export HOST=127.0.0.1
    - export PORT0=3000
    - npm run test

build-and-push-job:
  stage: build-and-push
  tags:
    - build-as-docker
  script:
    - source ci/set_docker_tag.sh
    - ci/build_and_deploy.sh
